CONTIKI_TARGET_DIRS = . dev
CONTIKI_TARGET_MAIN = $(addprefix $(OBJECTDIR)/,contiki-main.rel)

CONTIKI_SOURCEFILES += contiki-main.c
CONTIKI_SOURCEFILES += leds.c leds-arch.c

CLEAN += *.cc2540mini

CONTIKI_CPU=$(CONTIKI)/cpu/cc2540
include $(CONTIKI_CPU)/Makefile.cc2540
